# Make sure Docker is installed already on EC2 Instance
  name: Backend CD
  on:
    workflow_dispatch:
  jobs:
    build:
      name: Deploying Backend image to AWS EC2
      runs-on: self-hosted
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Docker Login
          run: |
            sudo docker login -u AWS -p $(aws ecr get-login-password) 715841355249.dkr.ecr.ap-south-1.amazonaws.com

        - name: Pull latest image 
          run: |
            sudo docker login -u AWS -p $(aws ecr get-login-password) 715841355249.dkr.ecr.ap-south-1.amazonaws.com
            sudo docker pull 715841355249.dkr.ecr.ap-south-1.amazonaws.com/glokelov/helm-jhoom:latest

        - name: Remove older image 
          run: sudo docker rm -f helm-jhoom-backend-container || true

        - name: Show all Docker Images
          run: sudo docker images

        - name: Run Docker Container
          run: sudo docker run -d -p 8080:8080 --name helm-jhoom-backend-container 715841355249.dkr.ecr.ap-south-1.amazonaws.com/glokelov/helm-jhoom:latest
