name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build docker image
      run: docker build -t helm-jhoom-backend
    - name: Push to DockerHub
      run: docker push 715841355249.dkr.ecr.ap-south-1.amazonaws.com/glokelov/helm-jhoom/helm-jhoom-backend:latest
