  name: Deploy Docker image to AWS ECS
  on:
    workflow_run:
      workflows: ["Push the Docker image to AWS ECR Repo."]
      types: 
        - completed
  jobs:
    Build:
      name: Build
      runs-on: self-hosted
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Pull latest image 
          run: sudo docker pull glokelov/helm-jhoom:latest

        - name: Remove older image 
          run: sudo docker rm -f helm-jhoom-backend-container || true

        - name: Run Docker Container
          run: sudo docker run -d -p 8080:8080 --name helm-jhoom-backend-container glokelov/helm-jhoom
