# Make sure Docker is installed already on EC2 Instance
  name: Frontend CD
  on:
    workflow_dispatch:
  jobs:
    build:
      name: Deploying docker image to AWS EC2
      runs-on: self-hosted
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Docker Login
          run: sudo docker login -u AWS -p $(aws ecr get-login-password) 715841355249.dkr.ecr.ap-south-1.amazonaws.com

        - name: Pull latest image 
          run: sudo docker pull 715841355249.dkr.ecr.ap-south-1.amazonaws.com/glokelov/jhoom-frontend:latest

        - name: Remove older image 
          run: sudo docker rm -f jhoom-frontend-container || true

        - name: Run Docker Container
          run: sudo docker run -p 8085:80 -d --name jhoom-frontend-container 715841355249.dkr.ecr.ap-south-1.amazonaws.com/glokelov/jhoom-frontend:latest
